/**
 * Datos mock de productos para ecommerce
 * The Lobby Beauty - Productos naturales de belleza
 */

import type { Producto, CategoriaProductoInfo } from "@/types";

export const categoriasProducto: CategoriaProductoInfo[] = [
  {
    id: 1,
    nombre: "Manicura",
    slug: "manicura",
    descripcion: "Esmaltes, tratamientos y accesorios para uñas",
    icono: "Hand",
  },
  {
    id: 2,
    nombre: "Pedicura",
    slug: "pedicura",
    descripcion: "Productos especializados para el cuidado de pies",
    icono: "Footprints",
  },
  {
    id: 3,
    nombre: "Facial",
    slug: "facial",
    descripcion: "Cremas, sérums y tratamientos faciales",
    icono: "Sparkles",
  },
  {
    id: 4,
    nombre: "Corporal",
    slug: "corporal",
    descripcion: "Hidratantes, exfoliantes y aceites corporales",
    icono: "Heart",
  },
  {
    id: 5,
    nombre: "Cabello",
    slug: "cabello",
    descripcion: "Champús, mascarillas y tratamientos capilares",
    icono: "Scissors",
  },
  {
    id: 6,
    nombre: "Accesorios",
    slug: "accesorios",
    descripcion: "Herramientas y accesorios de belleza",
    icono: "Gem",
  },
  {
    id: 7,
    nombre: "Kits",
    slug: "kits",
    descripcion: "Sets y packs especiales con descuento",
    icono: "Gift",
  },
];

export const productos: Producto[] = [
  // ============== MANICURA ==============
  {
    id: 1,
    nombre: "Esmalte Natural Rosa Nude",
    descripcion:
      "Esmalte de uñas 10-free con fórmula vegana y sin tóxicos. Color rosa nude elegante que combina con todo. Larga duración y brillo intenso sin dañar tus uñas. Formulado sin formaldehído, tolueno, DBP, formaldehyde resin, camphor, TPHP, xylene, ethyl tosylamide, parabenos ni fragancias sintéticas.",
    descripcion_corta: "Esmalte 10-free vegano color rosa nude",
    categoria: "manicura",
    precio: 12.95,
    imagen_url: "/images/productos/esmalte-rosa.jpg",
    stock: 50,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    ingredientes: ["Butyl Acetate", "Ethyl Acetate", "Nitrocellulose", "Adipic Acid", "Isopropyl Alcohol"],
    modo_uso: "Aplicar una capa base, dos capas de color y finalizar con top coat para mayor duración.",
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    nombre: "Esmalte Natural Rojo Cereza",
    descripcion:
      "Esmalte de uñas 10-free con un rojo intenso y vibrante. Fórmula vegana de alta cobertura que no requiere múltiples capas. Secado rápido y acabado brillante profesional.",
    descripcion_corta: "Esmalte 10-free vegano rojo intenso",
    categoria: "manicura",
    precio: 12.95,
    imagen_url: "/images/productos/esmalte-rojo.jpg",
    stock: 45,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 3,
    nombre: "Aceite Cutículas Nutritivo",
    descripcion:
      "Aceite 100% natural para cutículas con vitamina E, aceite de jojoba y extracto de lavanda. Nutre, suaviza y fortalece las cutículas secas o dañadas. Aroma relajante de lavanda natural.",
    descripcion_corta: "Aceite nutritivo con vitamina E y lavanda",
    categoria: "manicura",
    precio: 14.50,
    imagen_url: "/images/productos/aceite-cuticulas.jpg",
    stock: 35,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    ingredientes: ["Simmondsia Chinensis Oil", "Tocopherol", "Lavandula Angustifolia Oil", "Prunus Amygdalus Oil"],
    modo_uso: "Aplicar una gota en cada cutícula y masajear suavemente. Usar diariamente para mejores resultados.",
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    nombre: "Endurecedor de Uñas Natural",
    descripcion:
      "Tratamiento fortalecedor para uñas débiles y quebradizas. Fórmula enriquecida con biotina, calcio y queratina vegetal. Repara y protege desde la primera aplicación.",
    descripcion_corta: "Tratamiento fortalecedor con biotina",
    categoria: "manicura",
    precio: 16.95,
    imagen_url: "/images/productos/endurecedor.jpg",
    stock: 28,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    modo_uso: "Aplicar como base antes del esmalte o solo como tratamiento. Usar durante 2-4 semanas para resultados óptimos.",
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 5,
    nombre: "Top Coat Brillo Extremo",
    descripcion:
      "Capa superior de acabado ultra brillante y protección duradera. Seca en 60 segundos y protege el color hasta 7 días sin astillarse. Fórmula 10-free.",
    descripcion_corta: "Top coat secado rápido ultra brillante",
    categoria: "manicura",
    precio: 11.95,
    imagen_url: "/images/productos/top-coat.jpg",
    stock: 40,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 6,
    nombre: "Quitaesmalte Sin Acetona",
    descripcion:
      "Quitaesmalte suave y efectivo sin acetona ni químicos agresivos. Enriquecido con vitamina E y aceite de almendras para no resecar las uñas. Elimina incluso esmaltes oscuros sin esfuerzo.",
    descripcion_corta: "Quitaesmalte suave con vitamina E",
    categoria: "manicura",
    precio: 9.95,
    imagen_url: "/images/productos/quitaesmalte.jpg",
    stock: 60,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ============== PEDICURA ==============
  {
    id: 7,
    nombre: "Crema Pies Reparadora",
    descripcion:
      "Crema intensiva para pies secos y agrietados con manteca de karité, urea al 10% y extracto de caléndula. Hidrata profundamente y suaviza durezas. Ideal para talones agrietados.",
    descripcion_corta: "Crema intensiva con urea 10%",
    categoria: "pedicura",
    precio: 18.95,
    imagen_url: "/images/productos/crema-pies.jpg",
    stock: 42,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    ingredientes: ["Butyrospermum Parkii Butter", "Urea", "Calendula Officinalis Extract", "Aloe Barbadensis"],
    modo_uso: "Aplicar generosamente en pies limpios y secos, especialmente en talones. Usar mañana y noche.",
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 8,
    nombre: "Sales de Baño Relajantes",
    descripcion:
      "Sales de baño con magnesio del Mar Muerto, aceite esencial de eucalipto y menta. Relaja los pies cansados, reduce la hinchazón y elimina malos olores. Experiencia spa en casa.",
    descripcion_corta: "Sales del Mar Muerto con eucalipto",
    categoria: "pedicura",
    precio: 14.95,
    imagen_url: "/images/productos/sales-bano.jpg",
    stock: 55,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    modo_uso: "Disolver 2 cucharadas en agua tibia. Sumergir los pies durante 15-20 minutos.",
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 9,
    nombre: "Exfoliante Pies Piedra Pómez",
    descripcion:
      "Exfoliante cremoso con micropartículas de piedra pómez natural y aceite de coco. Elimina células muertas y suaviza la piel sin irritar. Deja los pies suaves como la seda.",
    descripcion_corta: "Exfoliante natural con piedra pómez",
    categoria: "pedicura",
    precio: 13.50,
    imagen_url: "/images/productos/exfoliante-pies.jpg",
    stock: 38,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 10,
    nombre: "Spray Refrescante Pies",
    descripcion:
      "Spray refrescante con mentol, árbol de té y aloe vera. Alivia el cansancio, refresca y desodoriza. Perfecto para llevar en el bolso y usar durante todo el día.",
    descripcion_corta: "Spray refrescante con mentol",
    categoria: "pedicura",
    precio: 11.95,
    precio_oferta: 9.95,
    imagen_url: "/images/productos/spray-pies.jpg",
    stock: 48,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ============== FACIAL ==============
  {
    id: 11,
    nombre: "Sérum Vitamina C",
    descripcion:
      "Sérum facial con 15% de vitamina C estabilizada, ácido hialurónico y vitamina E. Ilumina, unifica el tono y reduce manchas. Potente antioxidante que protege contra el envejecimiento.",
    descripcion_corta: "Sérum iluminador con 15% vitamina C",
    categoria: "facial",
    precio: 34.95,
    imagen_url: "/images/productos/serum-vitc.jpg",
    stock: 30,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    ingredientes: ["Ascorbic Acid", "Hyaluronic Acid", "Tocopherol", "Ferulic Acid", "Aloe Barbadensis"],
    modo_uso: "Aplicar 3-4 gotas por la mañana sobre piel limpia antes de la crema hidratante. Usar protector solar.",
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 12,
    nombre: "Crema Hidratante Facial",
    descripcion:
      "Crema hidratante ligera con ácido hialurónico, extracto de pepino y aloe vera. Hidratación 24h sin sensación grasa. Apta para todo tipo de pieles, incluso sensibles.",
    descripcion_corta: "Hidratante ligera con ácido hialurónico",
    categoria: "facial",
    precio: 28.95,
    imagen_url: "/images/productos/crema-facial.jpg",
    stock: 35,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 13,
    nombre: "Mascarilla Arcilla Verde",
    descripcion:
      "Mascarilla purificante con arcilla verde francesa, árbol de té y extracto de té verde. Limpia profundamente los poros, absorbe el exceso de grasa y matifica. Ideal para pieles mixtas y grasas.",
    descripcion_corta: "Mascarilla purificante de arcilla",
    categoria: "facial",
    precio: 19.95,
    imagen_url: "/images/productos/mascarilla-arcilla.jpg",
    stock: 40,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    modo_uso: "Aplicar una capa uniforme evitando contorno de ojos. Dejar actuar 10-15 minutos y aclarar con agua tibia.",
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 14,
    nombre: "Contorno de Ojos Antiedad",
    descripcion:
      "Tratamiento específico para el contorno de ojos con retinol vegetal, cafeína y péptidos. Reduce ojeras, bolsas y líneas de expresión. Textura gel-crema de rápida absorción.",
    descripcion_corta: "Contorno antiedad con retinol vegetal",
    categoria: "facial",
    precio: 32.95,
    imagen_url: "/images/productos/contorno-ojos.jpg",
    stock: 25,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 15,
    nombre: "Agua Micelar Natural",
    descripcion:
      "Agua micelar suave con agua de rosas, glicerina vegetal y extracto de manzanilla. Limpia, desmaquilla e hidrata en un solo paso. Sin necesidad de aclarado.",
    descripcion_corta: "Agua micelar con agua de rosas",
    categoria: "facial",
    precio: 15.95,
    imagen_url: "/images/productos/agua-micelar.jpg",
    stock: 50,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ============== CORPORAL ==============
  {
    id: 16,
    nombre: "Aceite Corporal Nutritivo",
    descripcion:
      "Aceite seco multifunción con argán, rosa mosqueta y vitamina E. Nutre, repara y da luminosidad a la piel. Absorción rápida sin dejar residuo graso. También apto para cabello.",
    descripcion_corta: "Aceite seco con argán y rosa mosqueta",
    categoria: "corporal",
    precio: 24.95,
    imagen_url: "/images/productos/aceite-corporal.jpg",
    stock: 32,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 17,
    nombre: "Exfoliante Corporal Café",
    descripcion:
      "Exfoliante corporal con granos de café arábica, aceite de coco y extracto de vainilla. Activa la circulación, reduce celulitis y deja la piel ultra suave. Aroma delicioso.",
    descripcion_corta: "Exfoliante anticelulítico de café",
    categoria: "corporal",
    precio: 21.95,
    imagen_url: "/images/productos/exfoliante-cafe.jpg",
    stock: 28,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    modo_uso: "Aplicar en piel húmeda con movimientos circulares. Insistir en zonas con celulitis. Aclarar con agua.",
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 18,
    nombre: "Manteca Corporal Karité",
    descripcion:
      "Manteca corporal ultra nutritiva con karité puro, cacao y aceite de almendras. Ideal para pieles muy secas. Repara y protege durante horas. Textura rica que se funde en la piel.",
    descripcion_corta: "Manteca ultra nutritiva de karité",
    categoria: "corporal",
    precio: 26.95,
    imagen_url: "/images/productos/manteca-karite.jpg",
    stock: 22,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 19,
    nombre: "Gel Ducha Avena",
    descripcion:
      "Gel de ducha suave con extracto de avena coloidal, miel y aloe vera. Limpia sin resecar, calma pieles sensibles e irritadas. pH equilibrado y sin sulfatos.",
    descripcion_corta: "Gel suave con avena y miel",
    categoria: "corporal",
    precio: 12.95,
    imagen_url: "/images/productos/gel-avena.jpg",
    stock: 45,
    es_natural: true,
    es_vegano: false,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ============== CABELLO ==============
  {
    id: 20,
    nombre: "Champú Natural Sin Sulfatos",
    descripcion:
      "Champú suave sin sulfatos, parabenos ni siliconas. Con extracto de coco, aloe vera y proteína de trigo. Limpia delicadamente respetando el cuero cabelludo. Apto para uso diario.",
    descripcion_corta: "Champú suave sin sulfatos ni siliconas",
    categoria: "cabello",
    precio: 16.95,
    imagen_url: "/images/productos/champu-natural.jpg",
    stock: 55,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 21,
    nombre: "Mascarilla Capilar Reparadora",
    descripcion:
      "Mascarilla intensiva con aceite de argán, keratina vegetal y manteca de mango. Repara el cabello dañado, aporta brillo y elimina el frizz. Resultados desde la primera aplicación.",
    descripcion_corta: "Mascarilla reparadora con argán",
    categoria: "cabello",
    precio: 22.95,
    imagen_url: "/images/productos/mascarilla-capilar.jpg",
    stock: 30,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    modo_uso: "Aplicar en cabello lavado y húmedo. Dejar actuar 5-10 minutos y aclarar. Usar 1-2 veces por semana.",
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 22,
    nombre: "Sérum Puntas Abiertas",
    descripcion:
      "Sérum reparador para puntas secas y abiertas con aceite de argán, jojoba y vitamina E. Sella las puntas, aporta brillo y protege del calor. No apelmaza el cabello.",
    descripcion_corta: "Sérum reparador de puntas",
    categoria: "cabello",
    precio: 18.95,
    imagen_url: "/images/productos/serum-puntas.jpg",
    stock: 35,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ============== ACCESORIOS ==============
  {
    id: 23,
    nombre: "Set Limas de Cristal",
    descripcion:
      "Set de 3 limas de cristal templado de diferentes tamaños. Limado suave y preciso que sella la uña evitando roturas. Lavables y reutilizables. Incluye estuche de viaje.",
    descripcion_corta: "Set 3 limas de cristal con estuche",
    categoria: "accesorios",
    precio: 19.95,
    imagen_url: "/images/productos/limas-cristal.jpg",
    stock: 40,
    es_natural: false,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 24,
    nombre: "Cepillo Facial Silicona",
    descripcion:
      "Cepillo limpiador facial de silicona suave con dos texturas. Limpia profundamente los poros y exfolia suavemente. Resistente al agua y fácil de limpiar. Apto para todo tipo de pieles.",
    descripcion_corta: "Cepillo limpiador de silicona",
    categoria: "accesorios",
    precio: 14.95,
    imagen_url: "/images/productos/cepillo-facial.jpg",
    stock: 50,
    es_natural: false,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 25,
    nombre: "Esponja Konjac Carbón",
    descripcion:
      "Esponja konjac 100% natural con carbón activo. Ideal para pieles mixtas y grasas. Limpia, exfolia y purifica. Biodegradable y sostenible. Duración aproximada de 3 meses.",
    descripcion_corta: "Esponja natural con carbón activo",
    categoria: "accesorios",
    precio: 8.95,
    imagen_url: "/images/productos/esponja-konjac.jpg",
    stock: 65,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 26,
    nombre: "Neceser Algodón Orgánico",
    descripcion:
      "Neceser de viaje fabricado en algodón orgánico certificado GOTS. Forro impermeable interior. Tamaño perfecto para llevar tus productos favoritos. Diseño exclusivo The Lobby Beauty.",
    descripcion_corta: "Neceser ecológico de algodón orgánico",
    categoria: "accesorios",
    precio: 24.95,
    imagen_url: "/images/productos/neceser.jpg",
    stock: 25,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: false,
    created_at: "2024-01-01T00:00:00Z",
  },

  // ============== KITS ==============
  {
    id: 27,
    nombre: "Kit Manicura Completo",
    descripcion:
      "Todo lo que necesitas para una manicura perfecta en casa. Incluye: esmalte rosa nude, top coat, aceite de cutículas, quitaesmalte sin acetona y lima de cristal. Ahorra un 20% comprando el kit.",
    descripcion_corta: "Kit completo manicura natural",
    categoria: "kits",
    precio: 49.95,
    precio_oferta: 39.95,
    imagen_url: "/images/productos/kit-manicura.jpg",
    stock: 20,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 28,
    nombre: "Kit Spa Pies",
    descripcion:
      "Tratamiento spa completo para tus pies. Incluye: sales de baño relajantes, exfoliante piedra pómez, crema reparadora intensiva y spray refrescante. El pack perfecto para mimar tus pies.",
    descripcion_corta: "Kit completo spa para pies",
    categoria: "kits",
    precio: 54.95,
    precio_oferta: 44.95,
    imagen_url: "/images/productos/kit-pies.jpg",
    stock: 18,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 29,
    nombre: "Kit Rutina Facial",
    descripcion:
      "Rutina facial completa para una piel radiante. Incluye: agua micelar, sérum vitamina C, crema hidratante y contorno de ojos. Todo lo esencial para el cuidado diario de tu rostro.",
    descripcion_corta: "Kit rutina facial completa",
    categoria: "kits",
    precio: 99.95,
    precio_oferta: 79.95,
    imagen_url: "/images/productos/kit-facial.jpg",
    stock: 15,
    es_natural: true,
    es_vegano: true,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 30,
    nombre: "Kit Regalo Natural Beauty",
    descripcion:
      "El regalo perfecto para amantes de la belleza natural. Incluye: aceite corporal nutritivo, gel ducha avena, manteca karité y neceser de algodón orgánico. Presentación en caja regalo.",
    descripcion_corta: "Kit regalo con productos estrella",
    categoria: "kits",
    precio: 79.95,
    precio_oferta: 64.95,
    imagen_url: "/images/productos/kit-regalo.jpg",
    stock: 12,
    es_natural: true,
    es_vegano: false,
    es_cruelty_free: true,
    activo: true,
    destacado: true,
    created_at: "2024-01-01T00:00:00Z",
  },
];

// Funciones de utilidad
export function getProductosPorCategoria(categoria: string): Producto[] {
  return productos.filter((p) => p.categoria === categoria && p.activo);
}

export function getProductoPorId(id: number): Producto | undefined {
  return productos.find((p) => p.id === id);
}

export function getProductosDestacados(): Producto[] {
  return productos.filter((p) => p.destacado && p.activo);
}

export function getProductosEnOferta(): Producto[] {
  return productos.filter((p) => p.precio_oferta && p.activo);
}

export function buscarProductos(termino: string): Producto[] {
  const terminoLower = termino.toLowerCase();
  return productos.filter(
    (p) =>
      p.activo &&
      (p.nombre.toLowerCase().includes(terminoLower) ||
        p.descripcion.toLowerCase().includes(terminoLower) ||
        p.categoria.toLowerCase().includes(terminoLower))
  );
}
